config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/index'
  devise_for :users
  root to: 'dashboard#show'
  resource :dashboard, only: [:show]
  resources :plans do
    resources :features
    # resources :subscriptions, :only [:new, :create]
  end
  resources :subscriptions do
    collection { get 'mysubs' }
    resources :usages
  end
  resources :checkout, only: [:create]
  resources :webhooks, only: [:create]
  # mount StripeEvent::Engine, at: '/webhooks'

  # get 'admin', to: 'dashboard#admin'
  # get 'buyer', to: 'dashboard#buyer'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

# Dashboard Controller that controls the admin and buyer dashboards
class DashboardController < ApplicationController
  def show; end
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

# Dashboard Helper
module DashboardHelper
end

app/views/dashboard/_admin.html.erb
<h1>Admin Dashboard</h1>
<p>You are signed in as <%= current_user.email%> </p>

<%# <%= link_to 'View Plans', plans_path(), method: :get %>
<%# <br> %>
<%# <%= link_to 'Add Plans', new_plan_path(), method: :get %> %> %>


<%= link_to 'Add User', new_user_invitation_path, method: :get %>
<br>
<%= link_to 'All Users', users_index_path, method: :get %>
<br>
<%= link_to 'Add Plans', new_plan_path, method: :get %>
<br>
<%= link_to 'All Plans', plans_path, method: :get %>

app/views/dashboard/_buyer.html.erb
Hello I am a buyer
<br>
<%= link_to 'View Plans', plans_path , method: :get %>
<br>
<%= link_to 'My Subscriptions', mysubs_subscriptions_path , method: :get %>
<br>

app/views/dashboard/buyer.html.erb
Hello I am a buyer

<%= render partial: 'sign_out'%>

<%= link_to 'Add Plans', destroy_user_session_path(), method: :delete %>

app/views/dashboard/show.html.erb
<%= render partial: current_user.admin? ? 'admin' : 'buyer' %>