config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/index'
  devise_for :users
  root to: 'dashboard#show'
  resource :dashboard, only: [:show]
  resources :plans do
    resources :features
    # resources :subscriptions, :only [:new, :create]
  end
  resources :subscriptions do
    collection { get 'mysubs' }
    resources :usages
  end
  resources :checkout, only: [:create]
  resources :webhooks, only: [:create]
  # mount StripeEvent::Engine, at: '/webhooks'

  # get 'admin', to: 'dashboard#admin'
  # get 'buyer', to: 'dashboard#buyer'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subscription.rb
# frozen_string_literal: true

class Subscription < ApplicationRecord
  # validates :amount, presence: true, numericality: true
  belongs_to :user
  belongs_to :plan
  has_many :usages, dependent: :destroy
end

app/controllers/subscriptions_controller.rb
# frozen_string_literal: true

class SubscriptionsController < ApplicationController
  def new
    # byebug
    @plan = Plan.find(params[:format])
    set_subscription
  end

  def create
    set_subscription
    set_plan
    @subscription.plan_id = @plan.id

    @subscription.user_id = current_user.id
    if @subscription.save
      byebug
      flash[:success] = 'You have subscribed sucessfully'
      @plan.features.each do |f|
        usage = Usage.new(:subscription_id => @subscription.id, :feature_id => f.id, :units => 0)
        usage.save
      end
      redirect_to subscription_path(@subscription)
        
    else
      flash[:error] = 'Subscription Failed'
      redirect_to new_subscription_path(@plan)
    end
  end

  def show
    @subscription = Subscription.find(params[:id])
    @plan = @subscription.plan
  end

  def mysubs
    @subscriptions = Subscription.includes(:plan).where(user_id: current_user.id)
  end

  private 

  def set_plan
    p = params[:subscription]
    @plan = Plan.find(p[:plan_id])
  end

  def set_subscription
    @subscription = Subscription.new
  end
end

app/helpers/subscriptions_helper.rb
# frozen_string_literal: true

module SubscriptionsHelper
end

app/views/subscriptions/_subscription.html.erb
<p>Subscribed</p>
<%= render partial: 'plans/plan', locals: {plan: subscription.plan, subscription: subscription } %>
<%# <%byebug%> %>
<%= subscription.amount %>
<%= subscription.created_at %>

app/views/subscriptions/mysubs.html.erb
<h1>Subscribed Plans</h1>
<%= render partial: 'subscription', :collection => @subscriptions %>

app/views/subscriptions/new.html.erb
<%= render partial: 'plans/plan', locals: { plan: @plan } %>
<br>
Hello there you are here for subscritpion are you sure?
<br>
<%# <% byebug %> %>
<%= button_to "Pay now!", checkout_index_path, params: { plan_id: params[:format] }, remote: true%>
<%= form_for  [@subscription]  do |f| %>
  <% f.text_field :plan_id, :value => params[:format]  %>
  <%# <%byebug%> %>
  <%= f.submit 'Yes' %>
<% end %>

app/views/subscriptions/show.html.erb
<%= render partial: @subscription %>