config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/index'
  devise_for :users
  root to: 'dashboard#show'
  resource :dashboard, only: [:show]
  resources :plans do
    resources :features
    # resources :subscriptions, :only [:new, :create]
  end
  resources :subscriptions do
    collection { get 'mysubs' }
    resources :usages
  end
  resources :checkout, only: [:create]
  resources :webhooks, only: [:create]
  # mount StripeEvent::Engine, at: '/webhooks'

  # get 'admin', to: 'dashboard#admin'
  # get 'buyer', to: 'dashboard#buyer'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/plan.rb
# frozen_string_literal: true

class Plan < ApplicationRecord
  # validates :monthly_income, presence: true, numericality: true
  # validates :name, presence: true, format: { with: /^[a-z]+$/i }
  has_many :features, dependent: :destroy
  has_many :subscriptions, dependent: :nullify
end

app/controllers/plans_controller.rb
# frozen_string_literal: true

class PlansController < ApplicationController
  def index
    @plans = Plan.all
  end

  def create
    @plan = Plan.new(plan_params)
    if @plan.save
      flash[:success] = 'Plan Successfully Created.'
      redirect_to @plan
    else
      flash[:error] = 'Failed to create Plan.'
      render 'new'
    end
  end

  def new
    @plan = Plan.new
  end

  def edit
    set_plan
  end

  def show
    set_plan
  end

  def update
    set_plan
    if @plan.update(plan_params)
      flash[:success] = 'Plan successfully updated.'
      redirect_to @plan
    else
      flash[:error] = 'Failed to update Plan.'
      redirect_to 'edit'
    end
  end

  def destroy
    Plan.destroy(params[:id])
  end

  private

  def set_plan
    @plan = Plan.find(params[:id])
  end

  def plan_params
    params.require(:plan).permit(:name, :code, :monthly_income)
  end
end

app/helpers/plan_helper.rb
# frozen_string_literal: true

module PlanHelper
end

app/views/plans/_admin_show.html.erb
<h1> Plan ID <%= @plan.id%></h1>
<br>
<tr>
  <td><%= @plan.name %></td>
  <td><%= @plan.code %></td>
  <td><%= @plan.monthly_income %></td>
  <td><%= link_to 'Edit', edit_plan_path(@plan) %></td>
  <td><%= link_to 'Destroy', plan_path(@plan),
    method: :delete,
    data: { confirm: 'Are you sure?' } %></td>
</tr>

<h1>Features: </h1>

<%= render @plan.features %>

<h1>Add Feature</h1>
<%= render partial: 'features/form', locals: {feature: @plan.features.build} %>

app/views/plans/_buyer_show.html.erb
<h1> Plan ID <%= @plan.id%></h1>
<br>
<tr>
      <td><%= @plan.name %></td>
      <td><%= @plan.code %></td>
      <td><%= @plan.monthly_income %></td>
        <td><%= link_to 'Subscribe', new_subscription_path(@plan) %></td>

</tr>

<h1>Features: </h1>
<%= render @plan.features%>

app/views/plans/_form.html.erb
<%= form_for @plan do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :code %>
  <%= f.text_field :code %><br>
  <%= f.label :monthly_income %>
  <%= f.number_field :monthly_income %><br>
  <%= f.submit 'Submit' %>
<% end %>

app/views/plans/_plan.html.erb
<tr>

  <td><%= plan.name %></td>
  <td><%= plan.code %></td>
  <td><%= plan.monthly_income %></td>
  <%# <%byebug%> %>
  <% if controller.controller_name == 'subscriptions' && params[:subscription_id] != nil%>
  <%# <%byebug%> %>
    <td><%= link_to 'Add Usage', subscription_usages_path(@subscription) %></td>
  <%elsif%>
    <td><%= link_to 'Show', plan_path(plan) %></td>
  <%end%>
  <% if current_user.admin? %>    
  <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
  <td><%= link_to 'Destroy', plan_path(plan),
    method: :delete,
    data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</tr>

app/views/plans/edit.html.erb
<%= render "form"%>

app/views/plans/index.html.erb
<h1>All Plans</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Code</th>
    <th>Monthly Income</th>
  </tr>

  <%= render partial: @plans %>
  </tr>
  
</table>

app/views/plans/new.html.erb
<%= render "form"%>

app/views/plans/show.html.erb
<%= if current_user.admin?
       render partial: 'admin_show'
    elsif current_user.buyer?
       render partial: 'buyer_show'
    end
%>