config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/index'
  devise_for :users
  root to: 'dashboard#show'
  resource :dashboard, only: [:show]
  resources :plans do
    resources :features
    # resources :subscriptions, :only [:new, :create]
  end
  resources :subscriptions do
    collection { get 'mysubs' }
    resources :usages
  end
  resources :checkout, only: [:create]
  resources :webhooks, only: [:create]
  # mount StripeEvent::Engine, at: '/webhooks'

  # get 'admin', to: 'dashboard#admin'
  # get 'buyer', to: 'dashboard#buyer'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/feature.rb
# frozen_string_literal: true

class Feature < ApplicationRecord
  #   validates :unit_price, :max_unit_limit, presence: true, numericality: true
  belongs_to :plan
  has_many :usages, dependent: :nullify
end

app/controllers/features_controller.rb
# frozen_string_literal: true

class FeaturesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @features = Feature.all
  end

  def create
    set_plan
    @feature = @plan.features.new(feature_params)
    if @feature.save
      flash[:notice] = 'You have successfully added a feature.'
      redirect_to plans_path
    else

      flash[:notice] = 'Failed to add the feature.'
      render 'new'
    end
  end

  def edit
    set_plan
    @feature = Features.find(params[:id])
  end

  def show
    set_plan
    @feature = Features.find(params[:id])
  end

  def new
    set_plan
    if 
    @feature = @plan.features.build
    end
  end

  def update
    set_feature
    if @feature.update(feature_params)
      flash[:success] = 'Feature Successfully Updated.'
      redirect_to @feature
    else
      flash[:error] = 'Feature Updation Failed.'
      redirect_to 'edit'
    end
  end

  def destroy
    set_feature
    @feature.destroy
  end

  private

  def set_plan
    @plan = Plan.find(params[:plan_id])
  end

  def set_feature
    @feature = Feature.find(params[:id])
  end

  def feature_params
    params.require(:feature).permit(:name, :unit_price, :max_unit_limit)
  end
  
end

app/helpers/features_helper.rb
# frozen_string_literal: true

module FeaturesHelper
end

app/views/features/_feature.html.erb
<tr>
  <td><%= feature.name %></td>
  <td><%= feature.unit_price %></td>
  <td><%= feature.max_unit_limit %></td>
  <%# <%byebug%> %>
  <% if current_user.admin? %>
  <%# <%byebug%> %>
    <td><%= link_to 'Show', plan_feature_path(@plan,feature) %></td>
    <td><%= link_to 'Edit', edit_plan_feature_path(@plan, feature) %></td>
    <td><%= link_to 'Destroy', plan_feature_path(@plan, feature),
    method: :delete,
      data: { confirm: 'Are you sure?' }%></td>
  <% elsif current_user.buyer? %>
  <%# <%byebug%> %>
    <%# <%= link_to 'Add Usage', new_plan_subscription_usage_path(@plan, @subscription, feature) %> %>
  <%end%> 
</tr> 
<br> 

app/views/features/_form.html.erb
<%# <% byebug %> %>
<%= form_for  [@plan, feature]  do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :unit_price %>
  <%= f.number_field :unit_price %><br>
  <%= f.label :max_unit_limit %>
  <%= f.number_field :max_unit_limit %><br>
  <%= f.submit 'Submit' %>
<% end %>

app/views/features/edit.html.erb
<%# <%byebug%> %>
<h1>Update Feature</h1>
<%= render partial: "form", locals: { feature: @feature } %>

app/views/features/index.html.erb
<h1>All Plans</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Unit Price</th>
    <th>Max Unit Limit</th>
  </tr>

  <%= render partial: @feature%>
  </tr>
  
</table>

app/views/features/new.html.erb
<%= render partial: 'form', locals: { plan: @plan, feature: @feature } %>

app/views/features/show.html.erb
<%= render partial: @feature %>